### ISSUE TITLE
Re-naming the package...?

### ISSUE THREAD

**Issue by asgrim** [Roave/ApiCompare#24]
I've noticed when explaining what the tool does, folks jump to conclusion that this is used for comparing HTTP/REST API versions. I wonder if renaming the package could alleviate this problem. Would be better to do it before we tag anything as naturally it's (ironically) a big BC break ;)

Not sure WHAT to suggest though for naming, feedback welcome on this.

**Comment by asgrim** [comment]
- `Roave\ABCD` (A BC Detector)
 - `Roave\BCBC` (BC Break Checker)
 - `Roave\BCBreakDetector`

**Comment by Majkl578** [comment]
SignatureComparer?
SignatureComparator?
SignatureComplianceChecker? (inspired by C/C++ abi-compliance-checker)

**Comment by gnumoksha** [comment]
Application Interface Comparator.

**Comment by Ocramius** [comment]
I would probably specialise the package to just deal with BC Breaks and keep the naming in that scope, so `roave/backwards-compatibility` or such.

**Comment by ntzm** [comment]
backward-compatibility-checker is my vote

**Comment by Majkl578** [comment]
Since this is not a _checker_ (as it returns non-zero code for BC issues), it should rather be `backward-compatibility-enforcer`.

**Comment by ntzm** [comment]
How about this-package-returns-a-non-zero-exit-code-if-your-code-is-not-backwards-compatible?

**Comment by Majkl578** [comment]
Hm, "check" is strange since it's a verb, package name should imho use noun. :/

**Comment by Ocramius** [comment]
Yeah, but most things in here are verbs, so let's roll with it 👍
