### ISSUE TITLE
Consider base comparator behavior as separate package

### ISSUE THREAD

**Issue by Majkl578** [Roave/ApiCompare#40]
Currently signature comparisons are hardcoded here.
Would be nice to make them reusable so maybe tools like PHPStan can reuse it later. Just an abstract API like `compareMethods($a, $b)` etc.

**Comment by Ocramius** [comment]
@Majkl578 this is already being worked on (for example in #38).

**Comment by Majkl578** [comment]
That is not a separate package.

**Comment by Ocramius** [comment]
Then there's some misunderstanding: I wouldn't make a separate package for well-known comparisons, but I am indeed making interfaces for all (most relevant) comparisons.
